### ISSUE TITLE
tracepoint_parse bug

### ISSUE THREAD

**Issue by xumn3348** [wkz/ply#34] opened 2021-11-05 15:33 UTC
trace event:
syscalls/sys_enter_close

result in:  offs = 16,  8+4=12, 16 != 12,  it maybe need the packed dealing .

name: sys_enter_close
ID: 623
format:
	field:unsigned short common_type;	offset:0;	size:2;	signed:0;
	field:unsigned char common_flags;	offset:2;	size:1;	signed:0;
	field:unsigned char common_preempt_count;	offset:3;	size:1;	signed:0;
	field:int common_pid;	offset:4;	size:4;	signed:1;

	field:int __syscall_nr;	offset:8;	size:4;	signed:1;
	field:unsigned int fd;	offset:16;	size:8;	signed:0;

print fmt: "fd: 0x%08lx", ((unsigned long)(REC->fd))

**Comment by wkz** [comment] 2021-11-25 22:42
Duplicate of iovisor/ply#75

**Closed as completed by wkz** 2021-11-25 22:42 UTC
